import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { useEffect } from 'react'
import MainTitle from '@/components/MainTitle'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Shrek Festival</title>
        <meta name="description" content="Generated by Shrek & Donkey" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      
      <MainTitle 
       mainTitle="WELCOME TO SHREK FESTIVAL"
      />

        <div className={styles.center}>
        <ul className={styles.musical_ul}>

       

        </ul>
          
        </div>

       
      </main>
    </>
  )
}
